services:
  coffeeapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: coffeeapi
    ports:
      - "8000:8000"
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - coffeeapi
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
