services:
  coffeeapi:
    build:
      context: .
      dockerfile: node.Dockerfile
    container_name: coffeeapi
    ports:
      - "8000:8000"
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - coffeeapi
    networks:
      - app_network

  s3-bucket:
    build:
      context: .
      dockerfile: s3rver.Dockerfile
    restart: always
    ports:
      - 9000:9000
    command: "node dist/s3.js"
    environment:
      AWS_ACCESS_KEY_ID: S3RVER
      AWS_SECRET_ACCESS_KEY: S3RVER
    volumes:
      - ".:/home/app"

networks:
  app_network:
    driver: bridge
